version = 1

[merge]
automerge_label = ["merge-breaking", "merge-feature", "merge-fix", "merge-none"]
blocking_labels = ["wip", "hold"]
delete_branch_on_merge = true
method = "rebase_fast_forward"

[approve]
# list of benevolant dictators ;)
auto_approve_usernames = ["simontheleg"]
