builds:
  - id: konf-go
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm
      - arm64
      - ppc64le
      - s390x
    goarm: [6, 7]
    ldflags:
      - -s -w -X github.com/simontheleg/konf-go/cmd.gitversion={{.Version}} -X github.com/simontheleg/konf-go/cmd.gitcommit={{.Commit}} -X github.com/simontheleg/konf-go/cmd.builddate={{.Date}}
