name: release
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # we need this, so GoReleaser has access to the whole history for generating changelog
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19.0
      - name: GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: 'v2.0.1'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
