on:
  push:
    branches:
      - main

jobs:
  new_semver_tag:
    permissions:
      contents: write
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: "0"
          ssh-key: ${{ secrets.SEMVER_TAG_SSH_KEY }}
      - name: tag
        uses: simontheleg/semver-tag-from-pr-action@v1.4.0
        with:
          # due to https://github.community/t/github-actions-workflow-not-triggering-with-tag-push/17053/8
          # we have to actually use a deploy-key here, so that the release flows push.tags section is working
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          label_major: merge-breaking
          label_minor: merge-feature
          label_patch: merge-fix
          label_none: merge-none
          repo_ssh_key: ${{ secrets.SEMVER_TAG_SSH_KEY}}
